### PR TITLE
added make rpm.

### PR DESCRIPTION
**Pull request by baron42bba**
Hi!

I added make rpm. Introduced RPM_VERSION in Makefile and placeholder in nagios-plugin-check_raid.spec file.
For which distribution is the spec file intended? As it's not working on CentOS6 and I would like to fix that.

Andreas Gerler

### CODE REVIEW

**Comment by glensc** [comment]
it's intended for [pld linux](https://github.com/pld-linux/nagios-plugin-check_raid). in fact it's place where the spec originated (plugin code was originally there)

i will redo your changes, making it more universal, not merging this directly.

**Comment by glensc** [comment]
added the support. please check does it work for you. if not, show me your errors.

also i think `Suggests` tag is not supported on CentOS

**Comment by glensc** [comment]
can you test it?

**Comment by baron42bba** [comment]
> On 03 Jul 2015, at 00:32, Elan Ruusamäe <notifications@github.com> wrote:
> 
> can you test it?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Hi Elan,

thanks for integration.
Makefile looks good.

Today I tried to install pld linux but gave up.
Instead I tweaked the spec file in a way to satisfy all distributions.
Suggests is not available on RHEL. Neither an %elsif construct.
I integrated the docs. The rpm can be installed on CentOS6 x86_64.
The src.rpm lacks some files though.
With 30 degrees celsius in town I don’t see right now how to fix it.

Next week doesn’t look good for me. Week of 07/13 I hope to work again on it.
You can check out my todays work:
https://github.com/baron42bba/nagios-plugin-check_raid/commit/55b51f52fbbfdfd908a803cd6a831fd33cd2b5aa

I will look into that src.rpm problem then. After that I am going to add some code to check BatteryBackupUnit status of HP Raid controller.
@work I have a broken one and run currently a quick hack to see the disabled cache and broken bbu.

Enjoy the weather!

so long...

Baron

— 

http://www.bundesbrandschatzamt.de/~baron
mailto:baron@bundesbrandschatzamt.de
jabber: baron@bundesbrandschatzamt.de AIM: baron42fmcb

**Comment by glensc** [comment]
no idea what your errors are there. i did not ask you to install pld-linux, just to test my changes on your system :)

and show your errors, then i can fix something

**Comment by glensc** [comment]
ping

**Comment by baron42bba** [comment]
> On 28 Jul 2015, at 19:01, Elan Ruusamäe <notifications@github.com> wrote:
> 
> ping
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Hi Elan,

sorry. Lot’s of things are going on currently.
I will definitely look into check_raid next week.

so long...

Andreas Gerler

— 

http://www.bundesbrandschatzamt.de/~baron
mailto:baron@bundesbrandschatzamt.de
jabber: baron@bundesbrandschatzamt.de AIM: baron42fmcb

**Comment by glensc** [comment]
i'm only asking output of your run, i.e what errors you get.

**Comment by glensc** [comment]
closing. works for me and no feedback in ticket

**Pull request closed without merging**
