### PR TITLE
Duplicate PR 205 from knorrie

### PR DESCRIPTION
**Pull request by Napsty**
Duplicates #205

### CODE REVIEW

**Comment by Napsty** [comment]
Verified on a HP Proliant G7 server running Debian 11 (Bullseye):

```
root@proliant:/tmp/nagios-plugin-check_raid# ./check_raid.sh 
OK: cciss:[/dev/sda(Smart Array P410i): Volume 0 (RAID 1(1+0)): OK, Drives(2): 1I-1-1,2I-1-5=OK, Cache: WriteCache FlashCache TotalMem:912 MiB Ratio:'25% Read / 75% Write' ReadMem:228 MiB WriteMem:684 MiB]; hpacucli:[Smart Array P410i[OK]: Array A(OK)[LUN1:OK]]
```

**Comment by Napsty** [comment]
credits should go to @knorrie

**Comment by glensc** [comment]
what is this different than https://github.com/glensc/nagios-plugin-check_raid/pull/205? why have the commits been squashed with an unhelpful commit message?

**Comment by Napsty** [comment]
because you asked me to?

> @Napsty you can carry the commits to your own branch and submit new PR with same commits, but do verify the changes are ok first.

https://github.com/glensc/nagios-plugin-check_raid/pull/205#issuecomment-1342183494

**Comment by glensc** [comment]
I asked to carry commits, but here I don't see any of the commits from previous pr, but new commit by you, so what is different here?

**Comment by Napsty** [comment]
OK so I misunderstood. Here everything is in one commit because I had manually patched the plugin with @knorrie's code changes a while ago (September 2021, https://github.com/glensc/nagios-plugin-check_raid/pull/205#issuecomment-911303477) and simply pushed that version into the PR. 
Just trying to help here, because it's a very important bug fix and without it the plugin won't work.

**Pull request closed without merging**
