### PR TITLE
tw_cli: Implement detailed BBU & Enclosure checks

### PR DESCRIPTION
**Pull request by robbat2**
$SUBJ

### CODE REVIEW

**Comment by glensc** [comment]
Excellent work! can you take look at the Travis failure? why it can't install DateTime module?

**Comment by glensc** [comment]
i think problem can be solved by adding `DateTime` to `cpanfile`

**Comment by glensc** [comment]
uh, the fatpacked check_raid.pl is now, 6.8M due the timezone data:
 
```
-rwxrwxr-x 1 glen glen 6.8M Feb 27 12:11 check_raid.pl*
```

how do you suggest to handle this?

**Comment by robbat2** [comment]
For the moment, the part of the code that uses it is actually commented out in my final submission, because I couldn't figure out if tw_cli localized the output at all (it was very unclear, I didn't have a localized system to test it on);

Until it's actually live, you can drop the timedate/datetime/date::parse entries in cpanfile.

If it DOES end up localizing it, we either need to force it to NOT localize for our calls (does it respect LC_ALL=C?) and parse manually, or bring in the timezone data :-(.

**Comment by glensc** [comment]
some other option would be to change distribution method, require them to install extra modules themselves

in my distro ([pld-linux](https://github.com/pld-linux/nagios-plugin-check_raid/blob/auto/th/nagios-plugin-check_raid-4.0.0-1/nagios-plugin-check_raid.spec#L81-L90)) i do not use the fatpacked script, but rather standard perl installation

**Comment by robbat2** [comment]
Yeah, for Gentoo I have it packaged the thin way, not fatpack at all:
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/nagios-plugin-check_raid

**Comment by glensc** [comment]
btw, you might want to automatically setup sudo rules from post-scriptlet:

https://github.com/pld-linux/nagios-plugin-check_raid/blob/auto/th/nagios-plugin-check_raid-4.0.0-1/nagios-plugin-check_raid.spec#L105-L114

and you should add runtime dep on `sudo`, most plugins use it

**Comment by robbat2** [comment]
Gentoo has tried very hard to NOT write sudoers rules for users as much as possible; but I will add a notice that users should use -S manually to do it.

**Comment by ixs** [comment]
Just some added information: I do not believe that tw_cli does *any* localization at all.

Whatever LANG setting, the timestamps always look like `27-Feb-2020` or `07-May-2022`.

**Pull request merged**
